#!/bin/sh

dunst &

wmname LG3D &

vmware-user-suid-wrapper &

~/.config/polybar/launch.sh &

picom --experimental-backends &

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/Pictures/octopus.png &

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- #

bspc config pointer_modifier mod1
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- #

bspc rule -a burp-StartBurp desktop='^2' state=floating
bspc rule -a "burp-StartBurp:*:Burp Suite Community Edition v2023.11.1.3 - Temporary Project" state=tiled

bspc rule -a discord desktop='^10'

bspc rule -a firefox desktop='^3'

bspc rule -a ghidra-Ghidra desktop='^2'
bspc rule -a "ghidra-Ghidra:*:Ghidra: NO ACTIVE PROJECT" state=tiled

bspc rule -a jetbrains-pycharm-ce desktop='^1' state=floating
bspc rule -a "jetbrains-pycharm-ce:*:Welcome to PyCharm" state=tiled
bspc rule -a "jetbrains-pycharm-ce:*:pythonProject – main.py" state=tiled

bspc rule -a Nm-connection-editor monitor='^1' state=floating
